[package]
name = "rusty-battleship"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = 2

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-as-inner = "0.6.0"
rand = "0.8.5"
strum = "0.26.2"
strum_macros = "0.26.4"
