[package]
name = "rusty-battleship"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = 2

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"